export const projects = [
  {
    number: '01',
    title: 'Shiksha Sahayak',
    tagline: '// RAG-powered educational AI assistant',
    accent: '#DDBEA9',
    description: 'AI learning assistant using RAG to retrieve relevant PDF knowledge and generate context-aware responses with multimodal and conversational capabilities.',
    problem: 'Students often struggle to find relevant information quickly across large PDFs and study materials. Generic AI responses may also provide answers without being grounded in their actual learning content.',
    solution: 'Built a RAG-based educational assistant that retrieves relevant information from uploaded PDFs before generating answers. Added conversational memory and multimodal capabilities to provide more interactive and context-aware learning support.',
    stack: ['Python', 'Flask', 'LangChain', 'Groq'],
    github: 'https://github.com/Nithishb03/shiksha-sahayaka-RAG-',
  },
  {
    number: '02',
    title: 'CarbonChain',
    tagline: '// AI-powered blockchain carbon verification',
    accent: '#2D6A4F',
    description: 'Blockchain-based carbon credit verification platform with AI-powered fraud detection, secure telemetry, and transparent on-chain settlement.',
    problem: 'Carbon credit verification can suffer from inaccurate sensor data, fraud, and lack of transparency in verification records. Traditional centralized systems make it difficult to independently verify emission data and prevent duplicate or fraudulent claims.',
    solution: 'Built a blockchain-based verification system combining IoT telemetry, AI-based anomaly detection, and smart contracts. Validated telemetry before recording verification results on-chain and enabling transparent carbon-credit settlement.',
    stack: ['React', 'Solidity', 'Ethereum', 'ONNX'],
    github: 'https://github.com/Nithishb03/carbon-credit-',
  },
  {
    number: '03',
    title: 'Sentinel — Continuous Authentication',
    tagline: '// Continuous behavioral authentication & anomaly detection',
    accent: '#DDBEA9',
    description: 'Continuous authentication system using behavioral anomaly detection to monitor user trust and secure active sessions.',
    problem: 'Traditional authentication verifies users mainly at login and may not detect account misuse after authentication. Behavioral changes and abnormal activity can allow unauthorized users to continue accessing an active session.',
    solution: 'Built a continuous authentication system that analyzes behavioral telemetry using Isolation Forest anomaly detection. Combined trust scoring, EMA smoothing, heartbeat monitoring, and fail-closed access control for continuous session protection.',
    stack: ['Python', 'Flask', 'Isolation Forest', 'Argon2id'],
    github: 'https://github.com/Nithishb03/IEH-AC',
  },
  {
    number: '04',
    title: 'Piezoelectric Energy Harvesting',
    tagline: '// DFT-guided ML for piezoelectric energy harvesting',
    accent: '#2D6A4F',
    description: 'DFT-guided energy harvesting system combining material simulation and ML-based piezoelectric voltage prediction.',
    problem: 'Piezoelectric energy output varies with material properties and environmental conditions such as pressure, temperature, and humidity. Accurately understanding and predicting voltage generation requires both material-level analysis and data-driven modeling.',
    solution: 'Developed a DFT-guided pipeline using Gaussian simulations and material-property analysis to generate meaningful features. Trained a Gradient Boosting model to predict piezoelectric voltage and integrated real-time inference for monitoring.',
    stack: ['Gaussian', 'MATLAB', 'Gradient Boosting', 'FastAPI'],
    github: 'https://github.com/Nithishb03/ZnO-piezoelectric-energy-harvesting',
  },
  {
    number: '05',
    title: 'Beam Crack Detection System',
    tagline: '// Computer-vision structural crack detection',
    accent: '#DDBEA9',
    description: 'ML-powered structural health monitoring dashboard that analyzes beam sensor and frequency data to estimate crack location, depth, and severity.',
    problem: 'Manual inspection of structural beams can be time-consuming and may miss small or early-stage cracks. A reliable automated approach is needed to identify visible cracks from structural images efficiently.',
    solution: 'Developed a computer-vision system that processes beam images to identify and analyze visible crack regions. Used image-processing techniques to automate crack detection and provide faster structural inspection support.',
    stack: ['React', 'Flask', 'scikit-learn', 'MATLAB'],
    github: 'https://github.com/Nithishb03/Beam_Crack_Detection_System',
  },
  {
    number: '06',
    title: 'Emergency Blood Donor Finder',
    tagline: '// Flask & PostgreSQL emergency donor platform',
    accent: '#2D6A4F',
    description: 'Flask-based platform connecting blood receivers, donors, and NGOs through blood group/location search, secure authentication, availability tracking, and donation management.',
    problem: 'Emergency blood requests can be delayed when compatible donors are difficult to find quickly. Manual coordination also makes donor availability and contact information difficult to manage.',
    solution: 'A Flask and PostgreSQL platform connects receivers with available donors using blood-group and location-based searches. Donor and NGO portals provide secure authentication, live availability updates, donor directories, and donation-history views.',
    stack: ['Flask', 'Python', 'PostgreSQL', 'SQLAlchemy'],
    github: 'https://github.com/Nithishb03/emergency-blood-donar-finder',
  },
];

export const skillsData = [
  { category: 'Programming', skills: ['Python', 'C', 'C++', 'JavaScript', 'SQL'] },
  { category: 'Web & Backend', skills: ['HTML', 'CSS', 'React.js', 'Flask', 'FastAPI', 'REST APIs'] },
  { category: 'Database & Data', skills: ['MySQL', 'SQLite', 'Redis', 'Git/GitHub'] },
  { category: 'AI & Machine Learning', skills: ['Machine Learning', 'RAG', 'NLP', 'Computer Vision', 'Scikit-learn', 'LangChain'] },
];

export const contactDetails = [
  { label: 'EMAIL', value: 'nithish7483@gmail.com', href: 'mailto:nithish7483@gmail.com' },
  { label: 'LINKEDIN', value: 'linkedin.com/in/nithishb03', href: 'https://www.linkedin.com/in/nithishb03/' },
  { label: 'GITHUB', value: 'github.com/Nithishb03', href: 'https://github.com/Nithishb03' },
  { label: 'LEETCODE', value: 'leetcode.com/u/_nithishb', href: 'https://leetcode.com/u/_nithishb/' },
  { label: 'PHONE', value: '+91 7483459123', href: 'tel:+917483459123' },
];
